let words = [
    {
        word: "python",
        hint: "programming language"
    },
    {
        word: "guitar",
        hint: "a musical instrument"
    },
    {
        word: "love",
        hint: "Strong affection"
    },
    {
        word: "ocean",
        hint: "One of the large bodies of water separating the continents."
    },
    {
        word: "gold",
        hint: "a yellow precious metal"
    },
    {
        word: "ghost",
        hint: "who scares children"
    },
    {
        word: "programmer",
        hint: "who create program"
    },
    {
        word: "coding",
        hint: "related to programming"
    },
    {
        word: "volcano",
        hint: "lava storage"
    },
    {
        word: "skater",
        hint: "skateboard player"
    },
    {
        word: "king",
        hint: "royal person"
    },
    {
        word: "gif",
        hint: "a file format for image"
    },
    {
        word: "mental",
        hint: "related to the mind"
    },
    {
        word: "map",
        hint: "diagram represent of an area"
    },
    {
        word: "island",
        hint: "land surrounded by water"
    },
    {
        word: "star",
        hint: "appeared in the evening"
    },
    {
        word: "chess",
        hint: "related to a indoor game"
    },
    {
        word: "grandpa",
        hint: "parent's father"
    },
    {
        word: "chicken",
        hint: "what animal has two legs"
    },
    {
        word: "dragon",
        hint: "a fiction animal"
    },
    {
        word: "silver",
        hint: "precious greyish-white metal"
    },
    {
        word: "flute",
        hint: "a musical instrument"
    },
    {
        word: "email",
        hint: "related to exchanging message"
    },
    {
        word: "air",
        hint: "related to a gas"
    },
    {
        word: "idea",
        hint: "a thought or suggestion"
    },
    {
        word: "server",
        hint: "related to computer or system"
    },
    {
        word: "search",
        hint: "act to find something"
    },
    {
        word: "key",
        hint: "small piece of metal"
    },
    {
        word: "egypt",
        hint: "a country name"
    },
    {
        word: "photo",
        hint: "representation of person or scene"
    },
    {
        word: "rain",
        hint: "related to a water"
    },
    {
        word: "rain",
        hint: "related to a water"
    },
    {
        word: "handsome",
        hint: "pretty boy"
    },
    {
        word: "single",
        hint: "do not love anyone"
    },
    {
        word: "sneaker",
        hint: "sport shoes"
    },
    {
        word: "tennis",
        hint: "a sport"
    },
    {
        word: "brain",
        hint: "body control"
    },
    {
        word: "television",
        hint: "thing use to watch movies at home"
    },
    {
        word: "computer",
        hint: "uses to code"
    },
    {
        word: "glasses",
        hint: "for eye protection"
    },
    {
        word: "social",
        hint: "people around us"
    },
    {
        word: "research",
        hint: "the process of learning about something"
    },
    {
        word: "train",
        hint: "a means of transport"
    },
    {
        word: "shark",
        hint: "a kind of fish"
    },
    {
        word: "flower",
        hint: "to give someone on an occasion"
    },
    {
        word: "playlist",
        hint: "including favorite songs"
    },
    {
        word: "cloud",
        hint: "made of steam"
    },
    {
        word: "astro",
        hint: "related to space"
    },
    {
        word: "physic",
        hint: "a subject"
    },
    {
        word: "hiphop",
        hint: "a culture from the street"
    },
    {
        word: "respect",
        hint: "an attitude of consideration or high regard"
    },
    {
        word: "communicate",
        hint: "to impart"
    },
    {
        word: "woman",
        hint: "an adult female human"
    },
    {
        word: "guess",
        hint: "To reach a partly unqualified conclusion"
    },
    {
        word: "erupt",
        hint: "To eject something violently"
    },
    {
        word: "another",
        hint: "An additional one of the same kind"
    },
    {
        word: "future",
        hint: "The time ahead"
    },
    {
        word: "hobby",
        hint: "An activity that one enjoys doing in one's spare time"
    },
    {
        word: "search",
        hint: "An attempt to find something"
    },
    {
        word: "close",
        hint: "An end or conclusion"
    },
    {
        word: "tired",
        hint: "To become sleepy or weary"
    },
    {
        word: "pencil",
        hint: "A paintbrush"
    },
    {
        word: "meeting",
        hint: "Event in which people come together"
    },
    {
        word: "number",
        hint: "Math symbol used for counting"
    },
    {
        word: "exchange",
        hint: "The act of trading"
    },
    {
        word: "canvas",
        hint: "Piece of fabric for oil painting"
    },
    {
        word: "garden",
        hint: "Space for planting flower and plant"
    },
    {
        word: "aesthetic",
        hint: "concerned with beauty or the appreciation of beauty"
    },
    {
        word: "anonymous",
        hint: "not identified by name; of unknown name"
    },
    {
        word: "bet",
        hint: "to risk money on the outcome of an event or situation; a wager"
    },
    {
        word: "hat",
        hint: "a covering for the head; a particular role or job"
    },
    {
        word: "hat",
        hint: "a covering for the head; a particular role or job"
    },
    {
        word: "dance",
        hint: "a series of movements performed to music"
    },
    {
        word: "grape",
        hint: "a small, sweet fruit with a thin skin that grows in clusters on vines"
    },
    { word: "apple", hint: "a round fruit with red, green or yellow skin and a white interior" },
    { word: "basic", hint: "fundamental, essential, or simple" },
    { word: "beach", hint: "a sandy or pebbly shore next to a body of water" },
    { word: "bread", hint: "a staple food made from flour, water, and yeast or baking powder" },
    { word: "brush", hint: "a tool with bristles or other fibers used for cleaning or painting" },
    { word: "chair", hint: "a piece of furniture with a back and seat for sitting on" },
    { word: "child", hint: "a young human being below the age of puberty" },
    { word: "dance", hint: "a series of movements performed to music" },
    { word: "earth", hint: "the planet we live on" },
    { word: "email", hint: "a message sent electronically over the internet" },
    { word: "field", hint: "an area of land used for growing crops or playing sports" },
    { word: "fruit", hint: "the sweet and fleshy product of a tree or other plant that contains seeds" },
    { word: "funny", hint: "causing laughter or amusement" },
    { word: "glass", hint: "a transparent or translucent material used for windows, drinking vessels, etc." },
    { word: "grape", hint: "a small, sweet fruit with a thin skin that grows in clusters on vines" },
    { word: "green", hint: "a color between blue and yellow, resembling the color of grass or foliage" },
    { word: "house", hint: "a building used for living in" },
    { word: "image", hint: "a representation of the external form of a person or thing" },
    { word: "juice", hint: "a liquid obtained from fruits or vegetables" },
    { word: "knife", hint: "a cutting instrument with a sharp blade and handle" },
    { word: "light", hint: "a form of energy that makes things visible or bright" },
    { word: "money", hint: "a medium of exchange in the form of coins, banknotes, or digital currency" },
    { word: "music", hint: "vocal or instrumental sounds combined in a way that produces beauty of form, harmony, and expression of emotion" },
    { word: "nurse", hint: "a person trained to care for the sick or infirm, especially in a hospital" },
    { word: "paper", hint: "a thin material used for writing or printing on" },
    { word: "party", hint: "a social gathering of invited guests, typically involving eating, drinking, and entertainment" },
    { word: "plant", hint: "a living organism that produces its own food through photosynthesis" },
    { word: "pizza", hint: "a dish of Italian origin consisting of a flat, round base of dough baked with toppings" },
    { word: "radio", hint: "a device for receiving and transmitting radio waves" },
    { word: "banana", hint: "a long curved fruit with yellow skin and soft sweet flesh" },
    { word: "camera", hint: "a device used to capture visual images" },
    { word: "carpet", hint: "a floor covering made of thick woven fabric" },
    { word: "cookie", hint: "a sweet baked food made from flour, sugar, and butter" },
    { word: "cotton", hint: "a soft white fibrous substance that surrounds the seeds of a tropical and subtropical plant" },
    { word: "danger", hint: "the possibility of harm or injury" },
    { word: "dollar", hint: "the basic monetary unit of the United States and other countries" },
    { word: "flower", hint: "the seed-bearing part of a plant, consisting of reproductive organs surrounded by colorful petals" },
    { word: "guitar", hint: "a stringed musical instrument with a fretted fingerboard and a body shaped like a figure-eight" },
    { word: "hockey", hint: "a team sport played on ice, in which players use sticks to shoot a small rubber puck into the opposing team's goal" },
    { word: "jacket", hint: "a short coat, typically with long sleeves and a front opening" },
    { word: "jungle", hint: "an area of land overgrown with dense forest and tangled vegetation, typically in the tropics" },
    { word: "kitten", hint: "a young domestic cat" },
    { word: "laptop", hint: "a portable computer that can be used on one's lap" },
    { word: "lemon", hint: "a yellow citrus fruit with acidic juice" },
    { word: "liquid", hint: "a substance that flows freely but is of constant volume" },
    { word: "lizard", hint: "a reptile with a long body, four legs, and a tapering tail" },
    { word: "mirror", hint: "a surface that reflects light, often used for seeing one's own reflection" },
    { word: "orange", hint: "a round fruit with a tough bright reddish-yellow rind and edible juicy pulp" },
    { word: "pencil", hint: "a tool for writing or drawing, consisting of a thin rod of graphite or other material enclosed in a long thin piece of wood" },
    { word: "pepper", hint: "a pungent, aromatic spice obtained from the dried berries of a climbing vine" },
    { word: "pickle", hint: "a small cucumber preserved in vinegar, brine, or a similar solution" },
    { word: "pocket", hint: "a small bag or pouch in a garment for carrying small items" },
    { word: "potato", hint: "a starchy plant tuber that is one of the world's most important food crops" },
    { word: "purple", hint: "a color intermediate between red and blue" },
    { word: "rabbit", hint: "a small furry animal with long ears and a short tail" },
    { word: "baby", hint: "a very young child, especially one that has not yet begun to walk or talk" },
    { word: "book", hint: "a written or printed work consisting of pages glued or sewn together along one side" },
    { word: "cake", hint: "a sweet baked food made from a mixture of flour, sugar, and other ingredients" },
    { word: "card", hint: "a small rectangular piece of stiff paper used for writing or printing on" },
    { word: "coin", hint: "a flat, typically round piece of metal used as money" },
    { word: "desk", hint: "a piece of furniture with a flat or sloping surface and typically with drawers, used for working at, writing on, or reading from" },
    { word: "door", hint: "a hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle" },
    { word: "fire", hint: "combustion or burning, in which substances combine chemically with oxygen from the air and typically give out bright light, heat, and smoke" },
    { word: "fish", hint: "a cold-blooded vertebrate animal that lives in water, typically with gills, fins, and a streamlined body" },
    { word: "flag", hint: "a piece of cloth or similar material, typically rectangular or triangular, with a design or colors symbolizing a country or institution" },
    { word: "game", hint: "an activity engaged in for diversion or amusement, often involving a set of rules or goals" },
    { word: "hair", hint: "any of the fine threadlike strands growing from the skin of humans and animals" },
    { word: "hand", hint: "the end part of a person's arm beyond the wrist, including the palm, fingers, and thumb" },
    { word: "home", hint: "the place where one lives permanently, especially as a member of a family or household" },
    { word: "idea", hint: "a thought or suggestion as to a possible course of action" },
    { word: "iron", hint: "a strong, hard magnetic silvery-gray metal" },
    { word: "joke", hint: "a thing that someone says to cause amusement or laughter" },
    { word: "kiss", hint: "touch or caress with the lips as a sign of love, sexual desire, or greeting" },
    { word: "lamp", hint: "a device for giving light, either one consisting of an electric bulb together with its holder and shade or cover, or one burning gas or oil and consisting of a wick or mantle and a glass shade" },
    { word: "leaf", hint: "a flattened structure of a higher plant, typically green and blade-like, that is attached to a stem directly or via a stalk" },
    { word: "life", hint: "the existence of an individual human being or animal" },
    { word: "line", hint: "a long, narrow mark or band" },
    { word: "love", hint: "an intense feeling of deep affection" },
    { word: "Example", hint: "A representative instance or illustration of something." },
    { word: "Weather", hint: "The state of the atmosphere at a particular place and time, with regard to variables such as temperature, moisture, wind velocity, and barometric pressure." },
    { word: "Include", hint: "Contain as part of a whole; have as a component." },
    { word: "Economy", hint: "The wealth and resources of a country or region, especially in terms of the production and consumption of goods and services." },
    { word: "Healthy", hint: "Possessing or enjoying good health or a sound and vigorous mentality." },
    { word: "Perform", hint: "Carry out, accomplish, or fulfill (an action, task, or function)." },
    { word: "Connect", hint: "Join together; link." },
    { word: "Install", hint: "Place or fix (equipment or machinery) in position ready for use." },
    { word: "Celebrate", hint: "Acknowledge (a significant or happy day or event) with a social gathering or enjoyable activity." },
    { word: "Discuss", hint: "Talk about (something) with a person or people." },
    { word: "Prepare", hint: "Make (something) ready for use or consideration." },
    { word: "Champion", hint: "A person who has surpassed all rivals in a sporting contest or other competition." },
    { word: "Destroy", hint: "Put an end to the existence of (something) by damaging or attacking it." },
    { word: "Explore", hint: "Travel in or through (an unfamiliar country or area) in order to learn about or familiarize oneself with it." },
    { word: "Improve", hint: "Make or become better." },
    { word: "Perform", hint: "Carry out, accomplish, or fulfill (an action, task, or function)." },
    { word: "Support", hint: "Bear all or part of the weight of; hold up." },
    { word: "Prepare", hint: "Make (something) ready for use or consideration." },
    { word: "Release", hint: "Allow or enable to escape from confinement; set free." },
    { word: "Advance", hint: "Move forward in a purposeful way." },
    { word: "Connect", hint: "Bring together or into contact so that a real or notional link is established." },
    { word: "Collect", hint: "Bring or gather together (things, typically when scattered or widespread)." },
    { word: "Inspect", hint: "Look at (someone or something) closely, typically to assess their condition or to discover any shortcomings." },
    { word: "Imagine", hint: "Form a mental image or concept of." },
    { word: "Replace", hint: "Take the place of." },
    { word: "Control", hint: "The power to influence or direct people's behavior or the course of events." },
    { word: "Persist", hint: "Continue firmly or obstinately in an opinion or a course of action in spite of difficulty, opposition, or failure." },
    { word: "Perform", hint: "Carry out, accomplish, or fulfill (an action, task, or function)." },
    { word: "Believe", hint: "Accept (something) as true; feel sure of the truth or existence of." },
    { word: "Discuss", hint: "Talk about (something) with a person or people." },
    { word: "Develop", hint: "Grow or cause to grow and become more mature, advanced, or elaborate." },
    { word: "Explore", hint: "Travel in or through (an unfamiliar country or area) in order to learn about or familiarize oneself with it." },
    { word: "Manage", hint: "Be in charge of (a company, establishment, or undertaking); administer; run." },
    { word: "Promote", hint: "Further the progress or development of (something, especially a cause, venture, or aim); support or actively encourage." },
    { word: "Receive", hint: "Be given, presented with, or paid (something)." },
    { word: "Prepare", hint: "Make (something) ready for use or consideration." },
    { word: "Realize", hint: "Become fully aware of (something) as a fact; understand clearly." },
    { word: "Persist", hint: "Continue firmly or obstinately in an opinion or a course of action in spite of difficulty, opposition, or failure." },
    { word: "Support", hint: "Bear all or part of the weight of; hold up." },
    { word: "Perform", hint: "Carry out, accomplish, or fulfill (an action, task, or function)." },
    { word: "Advance", hint: "Move forward in a purposeful way." },
    { word: "Believe", hint: "Accept (something) as true; feel sure of the truth or existence of." },
    { word: "Explore", hint: "Travel in or through (an unfamiliar country or area) in order to learn about or familiarize oneself with it." },
    { word: "Imagine", hint: "Form a mental image or concept of." },
    { word: "Collect", hint: "Bring or gather together (things, typically when scattered or widespread)." },
    { word: "Inspect", hint: "Look at (someone or something) closely, typically to assess their condition or to discover any shortcomings." },
    { word: "Replace", hint: "Take the place of." },
    { word: "Control", hint: "The power to influence or direct people's behavior or the course of events." },
    { word: "Persist", hint: "Continue firmly or obstinately in an opinion or a course of action in spite of difficulty, opposition, or failure." },
    { word: "Advance", hint: "Move forward in a purposeful way." },
    { word: "Connect", hint: "Bring together or into contact so that a real or notional link is established." },
    { word: "Inspect", hint: "Look at (someone or something) closely, typically to assess their condition or to discover any shortcomings." },
    { word: "Perform", hint: "Carry out, accomplish, or fulfill (an action, task, or function)." },
    { word: "Sunshine", hint: "Bright and direct sunlight." },
    { word: "Rainfall", hint: "The amount of rain that falls in a specific period." },
    { word: "Cloudy", hint: "Covered with clouds; overcast." },
    { word: "Breezy", hint: "Having a light and refreshing wind." },
    { word: "Drizzle", hint: "Light rain falling in fine drops." },
    { word: "Mistral", hint: "A strong, cold northwesterly wind in southern France." },
    { word: "Thunder", hint: "The loud noise and flash of light produced by lightning." },
    { word: "Forecast", hint: "A prediction of the weather conditions." },
    { word: "Tornado", hint: "A violent and destructive rotating column of air." },
    { word: "Hurricane", hint: "A large, powerful storm with strong winds and heavy rain." },
    { word: "Snowfall", hint: "The amount of snow that falls in a specific period." },
    { word: "Hailstorm", hint: "A storm with hailstones, usually accompanied by thunder and lightning." },
    { word: "Foggy", hint: "Filled or covered with thick clouds of water droplets." },
    { word: "Heatwave", hint: "A prolonged period of excessively hot weather." },
    { word: "Rainbow", hint: "A meteorological phenomenon that forms a circular arc of colors." },
    { word: "Cyclone", hint: "A large-scale, atmospheric circulation system characterized by rotating winds." },
    { word: "Drought", hint: "A prolonged period of abnormally low rainfall." },
    { word: "Muggy", hint: "Hot and humid, with a lack of fresh air." },
    { word: "Monsoon", hint: "A seasonal prevailing wind in the region of South and Southeast Asia." },
    { word: "Sleet", hint: "A mixture of rain and snow or ice pellets." },
    { word: "Gale", hint: "A very strong wind." },
    { word: "Hazy", hint: "Partially obscured or clouded by mist, smoke, or dust." },
    { word: "Chilly", hint: "Unpleasantly cool or cold." },
    { word: "Tropical", hint: "Relating to or characteristic of the tropics." },
    { word: "Overcast", hint: "Covered with clouds; dull or gloomy." },
    { word: "Thawing", hint: "The process of ice or snow melting." },
    { word: "Freezing", hint: "Below the freezing point of water; very cold." },
    { word: "Mild", hint: "Moderate in nature, intensity, or degree." },
    { word: "Stormy", hint: "Characterized by violent disturbances of the atmosphere." },
    { word: "Frosty", hint: "Covered with or resembling frost; very cold." },
    { word: "Sunrise", hint: "The time in the morning when the sun appears above the horizon." },
    { word: "Sunset", hint: "The time in the evening when the sun disappears below the horizon." },
    { word: "Windstorm", hint: "A storm with strong and violent winds." },
    { word: "Shower", hint: "A short period of rain or snowfall." },
    { word: "Rainy", hint: "Characterized by a lot of rain." },
    { word: "Tropical", hint: "Relating to or characteristic of the tropics." },
    { word: "Rice", hint: "A cereal grain and a staple food in many parts of the world." },
    { word: "Pizza", hint: "A savory dish consisting of a round, flattened base of dough topped with various ingredients." },
    { word: "Soup", hint: "A liquid food, typically savory and made by boiling meat, fish, or vegetables." },
    { word: "Bread", hint: "A staple food made from flour, water, and yeast, typically baked." },
    { word: "Cake", hint: "A sweet baked dessert made from flour, sugar, eggs, and butter or oil." },
    { word: "Pasta", hint: "A staple food made from unleavened dough of wheat or other grains." },
    { word: "Steak", hint: "A slice of meat, typically beef, cooked by broiling, frying, or grilling." },
    { word: "Salad", hint: "A cold dish consisting of mixed vegetables, often with added meat, fish, or cheese." },
    { word: "Sushi", hint: "A Japanese dish consisting of vinegared rice with various toppings." },
    { word: "Burger", hint: "A sandwich consisting of a cooked patty of ground meat, usually beef." },
    { word: "Taco", hint: "A Mexican dish consisting of a tortilla filled with various ingredients." },
    { word: "Fries", hint: "Thin pieces of potato that have been deep-fried until crispy." },
    { word: "Cheese", hint: "A dairy product made from pressed milk curds." },
    { word: "Fish", hint: "A limbless cold-blooded vertebrate animal with gills and fins." },
    { word: "Chicken", hint: "A domestic fowl bred for its flesh and eggs." },
    { word: "Noodle", hint: "A food paste or dough made from wheat flour, water, and often egg." },
    { word: "Egg", hint: "The oval reproductive body laid by a female bird, typically containing a developing embryo." },
    { word: "Toast", hint: "Sliced bread browned by exposure to radiant heat." },
    { word: "Apple", hint: "The round fruit of a tree of the rose family, which typically has thin green or red skin." },
    { word: "Chocolate", hint: "A food made from roasted and ground cacao seeds." },
    { word: "Banana", hint: "A long curved fruit with a yellow or green skin." },
    { word: "Ramen", hint: "A Japanese dish consisting of Chinese-style wheat noodles served in a meat or fish-based broth." },
    { word: "Pancake", hint: "A thin, flat cake made of batter and cooked on a hot griddle or frying pan." },
    { word: "Hotdog", hint: "A cooked sausage served in a sliced bun, often garnished with condiments." },
    { word: "Shrimp", hint: "A small, swimming crustacean with an elongated body and a long, narrow fan-like tail." },
    { word: "Sausage", hint: "A cylindrical meat product usually made from ground meat." },
    { word: "Curry", hint: "A dish of meat, vegetables, etc., cooked in an Indian-style sauce." },
    { word: "Donut", hint: "A small fried cake of sweetened dough, typically in the shape of a ball or ring." },
    { word: "Pineapple", hint: "A tropical fruit with a tough outer skin, sweet yellow flesh, and a crown of spiky leaves." },
    { word: "Yogurt", hint: "A semi-solid sourish food prepared from milk fermented by added bacteria." },
    { word: "Popcorn", hint: "A type of corn that expands and puffs up when heated." },
    { word: "Sushi", hint: "A Japanese dish consisting of vinegared rice with various toppings." },
    { word: "Muffin", hint: "A small, cup-shaped baked bread product." },
    { word: "Pudding", hint: "A sweet or savory soft dish served after the main course of a meal." },
    { word: "Ice cream", hint: "A frozen sweet food made from dairy products." },
    { word: "Waffle", hint: "A crisp, batter cake cooked in a waffle iron." },
    { word: "Omelette", hint: "A dish made from beaten eggs, cooked with butter or oil in a frying pan." },
    { word: "Salsa", hint: "A spicy tomato-based sauce." },
    { word: "Hamburger", hint: "A sandwich consisting of a cooked patty of ground meat, usually beef." },
    { word: "Sausage", hint: "A cylindrical meat product usually made from ground meat." },
    { word: "Book", hint: "A written or printed work consisting of pages bound together." },
    { word: "Pen", hint: "A device used to write or draw with ink." },
    { word: "Chair", hint: "A piece of furniture for one person to sit on, typically with a back and four legs." },
    { word: "Table", hint: "A piece of furniture with a flat top and one or more legs." },
    { word: "Phone", hint: "A telecommunications device used to make calls or send messages." },
    { word: "Key", hint: "A small piece of shaped metal used to operate a lock or start an engine." },
    { word: "Car", hint: "A road vehicle with an engine, four wheels, and seating for a small number of people." },
    { word: "Bike", hint: "A pedal-powered vehicle with two wheels." },
    { word: "Bag", hint: "A flexible container with an opening at the top, used for carrying items." },
    { word: "Shirt", hint: "A garment for the upper body with a collar, sleeves, and buttons." },
    { word: "Shoes", hint: "Footwear that covers and protects the feet." },
    { word: "Hat", hint: "A covering for the head, typically with a brim and a shaped crown." },
    { word: "Clock", hint: "A device for measuring and showing the time." },
    { word: "Glasses", hint: "A pair of lenses set in a frame worn on the nose and ears to correct vision." },
    { word: "Camera", hint: "A device used to capture and store photographs or videos." },
    { word: "Laptop", hint: "A portable computer small enough to use on one's lap." },
    { word: "Remote", hint: "A device used to control a television, DVD player, or other electronic equipment." },
    { word: "Chair", hint: "A piece of furniture for one person to sit on, typically with a back and four legs." },
    { word: "Tablet", hint: "A portable computer with a touchscreen display." },
    { word: "Spoon", hint: "An eating or cooking utensil with a small shallow bowl and a long handle." },
    { word: "Cup", hint: "A small open container used for drinking." },
    { word: "Plate", hint: "A flat dish used for serving food." },
    { word: "Knife", hint: "A utensil with a cutting blade and a handle." },
    { word: "Fork", hint: "A utensil with two or more prongs used for eating or serving food." },
    { word: "Brush", hint: "A tool with bristles used for cleaning or grooming." },
    { word: "Scissors", hint: "A tool with two sharp blades used for cutting." },
    { word: "Bottle", hint: "A container with a narrow neck used for storing liquids." },
    { word: "Umbrella", hint: "A portable canopy used to provide shade or protection from rain." },
    { word: "Mirror", hint: "A reflective surface used for viewing oneself or reflecting light." },
    { word: "Fan", hint: "A device used to create a current of air." },
    { word: "Wallet", hint: "A small, flat case used to carry personal items such as money and cards." },
    { word: "Candle", hint: "A cylindrical stick of wax with a wick in the middle, used for lighting." },
    { word: "Bed", hint: "A piece of furniture for sleeping or resting on." },
    { word: "Towel", hint: "A piece of absorbent fabric used for drying or wiping." },
    { word: "Shower", hint: "A device for washing oneself, typically consisting of a spray nozzle and a faucet." },
    { word: "Toothbrush", hint: "A small brush used for cleaning teeth." },
    { word: "Toothpaste", hint: "A paste or gel used for cleaning teeth." },
    { word: "Pillow", hint: "A rectangular cushion used to support the head during sleep or rest." },
    { word: "Curtain", hint: "A piece of fabric hung to cover a window or separate a space." },
    { word: "Rug", hint: "A floor covering made of thick woven material or animal skin." },
    { word: "Radio", hint: "A device used to receive and play broadcast sound signals." },
    { word: "Headphones", hint: "A pair of small speakers worn over the ears to listen to audio privately." },
    { word: "Microwave", hint: "An oven that cooks or heats food by microwaves." },
    { word: "Fridge", hint: "A household appliance used for keeping food and drinks cool." },
    { word: "Bowl", hint: "A round, deep dish used for serving food or holding liquids." },
    { word: "Cupboard", hint: "A piece of furniture with shelves or drawers used for storage." },
    { word: "Couch", hint: "A long upholstered piece of furniture for seating several people." },
    { word: "Speaker", hint: "A device that converts electrical signals into sound." },
    { word: "Lamp", hint: "A device that gives off light, typically consisting of a bulb and a shade." },
    { word: "Shirt", hint: "A garment for the upper body with a collar, sleeves, and buttons." },
    { word: "Pants", hint: "A piece of clothing worn from the waist to the ankles, covering both legs separately." },
    { word: "Dress", hint: "A one-piece garment for women or girls that covers the body and extends down over the legs." },
    { word: "Skirt", hint: "A garment worn by women or girls that hangs from the waist and covers all or part of the legs." },
    { word: "Socks", hint: "A covering for the foot and lower part of the leg, typically made of cotton or wool." },
    { word: "Shoes", hint: "Footwear that covers and protects the feet." },
    { word: "Coat", hint: "A garment worn over other clothing for warmth or protection from the weather." },
    { word: "Jacket", hint: "A short coat, typically extending to the waist." },
    { word: "Sweater", hint: "A knitted garment typically made of wool or cotton, worn on the upper body." },
    { word: "Hat", hint: "A covering for the head, typically with a brim and a shaped crown." },
    { word: "Gloves", hint: "Coverings for the hands, typically with separate sheaths for each finger and the thumb." },
    { word: "Scarf", hint: "A length or square of fabric worn around the neck or head for warmth or decoration." },
    { word: "Belt", hint: "A strip of leather or other material worn around the waist to hold clothing in place." },
    { word: "Tie", hint: "A narrow strip of fabric worn around the neck, typically with a shirt and suit." },
    { word: "Blouse", hint: "A woman's loose-fitting upper garment resembling a shirt." },
    { word: "Jeans", hint: "Casual pants made of denim, typically with pockets and a zipper." },
    { word: "Shorts", hint: "Garments that cover the pelvic area and part of the thighs, worn in hot weather." },
    { word: "Suit", hint: "A set of matching garments, typically consisting of a jacket and trousers or a skirt." },
    { word: "Trousers", hint: "An outer garment for the lower body, covering both legs separately." },
    { word: "Vest", hint: "A sleeveless garment worn on the upper body, often as part of a suit." },
    { word: "T-shirt", hint: "A casual short-sleeved shirt, typically made of cotton and without a collar." },
    { word: "Blazer", hint: "A lightweight jacket, typically worn as part of a uniform or with smart casual attire." },
    { word: "Hoodie", hint: "A sweatshirt or jacket with a hood." },
    { word: "Pajamas", hint: "Loose-fitting garments worn for sleeping or lounging at home." },
    { word: "Robe", hint: "A loose-fitting outer garment, often worn before or after bathing." },
    { word: "Underwear", hint: "Clothing worn next to the skin, including bras and panties for women and briefs or boxers for men." },
    { word: "Swimsuit", hint: "A garment worn for swimming or bathing." },
    { word: "Raincoat", hint: "A waterproof coat worn to protect against rain." },
    { word: "Tights", hint: "A close-fitting one-piece garment for the lower body, usually made of nylon or cotton." },
    { word: "Bikini", hint: "A skimpy two-piece bathing suit for women." },
    { word: "Sarong", hint: "A loose-fitting garment made of a long strip of cloth, worn as a skirt or dress." },
    { word: "Poncho", hint: "A large, loose garment with a hole in the center for the head, worn as a raincoat." },
    { word: "Leggings", hint: "Tight-fitting stretch pants, typically worn by women or girls." },
    { word: "Bra", hint: "A woman's undergarment worn to support the breasts." },
    { word: "Thong", hint: "A skimpy undergarment, typically consisting of a strip of fabric passing between the buttocks." },
    { word: "Bowtie", hint: "A type of necktie that consists of a ribbon of fabric tied around the collar in a symmetrical manner." },
    { word: "Pocket", hint: "A small pouch or compartment in a garment used for carrying small items." },
    { word: "Button", hint: "A small disk or knob used for fastening two parts of a garment by being pushed through a buttonhole." },
    { word: "Zipper", hint: "A device consisting of two strips of fabric with metal or plastic teeth used for fastening." },
    { word: "Collar", hint: "The part of a shirt, dress, or coat that fits around or frames the neck." },
    { word: "Head", hint: "The upper part of the human body, containing the brain, eyes, nose, mouth, and ears." },
    { word: "Eye", hint: "The organ of sight, located in the sockets of the skull." },
    { word: "Nose", hint: "The part projecting above the mouth on the face, used for breathing and smelling." },
    { word: "Mouth", hint: "The opening in the face through which food is taken in and vocal sounds are emitted." },
    { word: "Ear", hint: "The organ of hearing, located on the sides of the head." },
    { word: "Hair", hint: "The thread-like strands that grow from the skin, especially on the scalp." },
    { word: "Neck", hint: "The part of the body that connects the head to the rest of the torso." },
    { word: "Shoulder", hint: "The joint connecting the upper arm or forelimb to the body." },
    { word: "Arm", hint: "The upper limb of the human body, extending from the shoulder to the hand." },
    { word: "Elbow", hint: "The joint between the forearm and the upper arm." },
    { word: "Hand", hint: "The terminal part of the human arm, consisting of the palm and fingers." },
    { word: "Finger", hint: "One of the five digits on the hand, used for grasping and manipulating objects." },
    { word: "Thumb", hint: "The short, thick first digit of the hand, set lower and apart from the other four." },
    { word: "Chest", hint: "The front surface of the body between the neck and the abdomen." },
    { word: "Back", hint: "The posterior part of the human body, from the shoulders to the hips." },
    { word: "Waist", hint: "The part of the human body between the ribs and the hips, often narrower than the chest and abdomen." },
    { word: "Hip", hint: "The joint between the thigh and the pelvis." },
    { word: "Leg", hint: "The limb of the human body extending from the hip to the ankle, consisting of the thigh, calf, and foot." },
    { word: "Knee", hint: "The joint between the thigh and the lower leg in humans." },
    { word: "Foot", hint: "The terminal part of the leg below the ankle, on which a person stands or walks." },
    { word: "Toe", hint: "One of the five digits on the foot, used for balance and walking." },
    { word: "Skin", hint: "The thin layer of tissue forming the outer covering of the body." },
    { word: "Nail", hint: "A thin horny translucent plate covering the upper surface of the end of each finger and toe." },
    { word: "Muscle", hint: "A band or bundle of fibrous tissue that has the ability to contract, producing movement or maintaining tension." },
    { word: "Bone", hint: "The hard, rigid form of connective tissue that makes up the skeleton of vertebrates." },
    { word: "Joint", hint: "The point where two or more bones are connected." },
    { word: "Lip", hint: "Either of the two fleshy parts forming the upper and lower edges of the mouth." },
    { word: "Tongue", hint: "The fleshy muscular organ in the mouth that is used for tasting, swallowing, and speaking." },
    { word: "Teeth", hint: "Hard bony structures in the jaws used for biting and chewing food." },
    { word: "Gum", hint: "The firm connective tissue that surrounds the base of the teeth." },
    { word: "Beach", hint: "A sandy or pebbly shore by the ocean or a lake." },
    { word: "Park", hint: "A public green space for recreational activities." },
    { word: "Cafe", hint: "A small restaurant or coffeehouse." },
    { word: "Museum", hint: "A building that showcases artifacts and artworks." },
    { word: "Market", hint: "A place where goods or commodities are bought and sold." },
    { word: "Mountain", hint: "A large natural elevation of the earth's surface." },
    { word: "Bridge", hint: "A structure that connects two points over an obstacle." },
    { word: "Garden", hint: "A piece of land used for growing flowers, plants, or vegetables." },
    { word: "Island", hint: "A piece of land surrounded by water." },
    { word: "Lake", hint: "A large body of water surrounded by land." },
    { word: "Forest", hint: "A large area covered with trees and undergrowth." },
    { word: "Cinema", hint: "A place where movies are shown on a big screen." },
    { word: "Square", hint: "An open area in a town or city, often with buildings surrounding it." },
    { word: "Castle", hint: "A large fortified building, typically from medieval times." },
    { word: "River", hint: "A large natural flowing watercourse." },
    { word: "Zoo", hint: "A facility that houses and displays a collection of wild animals." },
    { word: "Library", hint: "A building that holds books and other materials for reading and studying." },
    { word: "Stadium", hint: "A large sports arena or venue for public events." },
    { word: "Hotel", hint: "A place that provides lodging, usually for travelers." },
    { word: "Church", hint: "A building used for public Christian worship." },
    { word: "School", hint: "An institution for teaching and learning." },
    { word: "Beach", hint: "A sandy or pebbly shore by the ocean or a lake." },
    { word: "Cave", hint: "A hollow space in the earth or a mountain." },
    { word: "Bridge", hint: "A structure that connects two points over an obstacle." },
    { word: "Gym", hint: "A place for physical exercise and fitness training." },
    { word: "Farm", hint: "An area of land used for cultivating crops or raising livestock." },
    { word: "Tower", hint: "A tall, narrow structure, often part of a building or monument." },
    { word: "Harbor", hint: "A sheltered area of water where ships and boats can dock." },
    { word: "Family", hint: "A group of people who are related by blood or marriage." },
    { word: "Mother", hint: "A female parent who gives birth to or raises a child." },
    { word: "Father", hint: "A male parent who begets or raises a child." },
    { word: "Sister", hint: "A female sibling; a girl or woman who has the same parents as another person." },
    { word: "Brother", hint: "A male sibling; a boy or man who has the same parents as another person." },
    { word: "Daughter", hint: "A female child; a girl or woman in relation to her parents." },
    { word: "Son", hint: "A male child; a boy or man in relation to his parents." },
    { word: "Grandmother", hint: "The mother of one's father or mother." },
    { word: "Grandfather", hint: "The father of one's father or mother." },
    { word: "Aunt", hint: "The sister of one's father or mother, or the wife of one's uncle." },
    { word: "Uncle", hint: "The brother of one's father or mother, or the husband of one's aunt." },
    { word: "Cousin", hint: "A child of one's uncle or aunt; a relative in the same generation as oneself." },
    { word: "Niece", hint: "A daughter of one's brother or sister, or of one's brother-in-law or sister-in-law." },
    { word: "Nephew", hint: "A son of one's brother or sister, or of one's brother-in-law or sister-in-law." },
    { word: "Husband", hint: "A married man in relation to his wife." },
    { word: "Wife", hint: "A married woman in relation to her husband." },
    { word: "Marriage", hint: "The legally or formally recognized union of two people as partners in a personal relationship." },
    { word: "Parents", hint: "A person's mother and father." },
    { word: "Cooking", hint: "The process of preparing food by applying heat." },
    { word: "Recipe", hint: "A set of instructions for preparing a particular dish." },,
    { word: "Stir", hint: "To mix ingredients in a circular motion using a spoon or utensil." },
    { word: "Chop", hint: "To cut food into small, irregular pieces." },
    { word: "Bake", hint: "To cook food using dry heat, typically in an oven." },
    { word: "Boil", hint: "To heat a liquid until bubbles form and it reaches its boiling point." },
    { word: "Simmer", hint: "To cook gently in a liquid just below the boiling point." },
    { word: "Grill", hint: "To cook food directly over an open flame or on a hot surface." },
    { word: "Roast", hint: "To cook food by exposing it to dry heat, usually in an oven." },
    { word: "Fry", hint: "To cook food in hot oil or fat." },
    { word: "Saute", hint: "To cook food quickly in a small amount of oil or fat." },
    { word: "Season", hint: "To add salt, pepper, herbs, or spices to enhance the flavor of food." },
    { word: "Taste", hint: "To sample food to assess its flavor or quality." },
    { word: "Mix", hint: "To combine ingredients together thoroughly." },
    { word: "Whisk", hint: "To beat or stir rapidly using a whisk." },
    { word: "Knead", hint: "To work dough by pressing and folding it with the hands." },
    { word: "Roll", hint: "To flatten dough using a rolling pin." },
    { word: "Slice", hint: "To cut food into thin, flat pieces." },
    { word: "Dice", hint: "To cut food into small, uniform cubes." },
    { word: "Peel", hint: "To remove the outer skin or rind of a fruit or vegetable." },
    { word: "Grate", hint: "To shred food into fine pieces using a grater." },
    { word: "Steam", hint: "To cook food using steam generated by boiling water." },
    { word: "Blend", hint: "To mix or combine ingredients until smooth and uniform." },
    { word: "Sauce", hint: "A liquid or semi-solid mixture served with food to add flavor or moisture." },
    { word: "Garnish", hint: "To decorate or adorn a dish with additional items for visual appeal." },
    { word: "Marinate", hint: "To soak food in a seasoned liquid to enhance its flavor." },
    { word: "Sieve", hint: "To strain or separate finer particles from coarser ones using a sieve." },
    { word: "Preheat", hint: "To heat an oven or cooking surface to a specific temperature before use." },
    { word: "Melt", hint: "To convert a solid substance into a liquid by heating it." },
    { word: "Drizzle", hint: "To pour a thin stream of liquid over food in a fine, controlled manner." },
    { word: "Doctor", hint: "A medical professional who treats and diagnoses illnesses." },
    { word: "Teacher", hint: "An educator who imparts knowledge and guides students in learning." },
    { word: "Engineer", hint: "A person who designs, builds, or maintains engines, machines, or structures." },
    { word: "Lawyer", hint: "A professional who provides legal advice and represents clients in court." },
    { word: "Nurse", hint: "A healthcare professional who provides care and assistance to patients." },
    { word: "Artist", hint: "A person who creates visual or performing art as a profession or hobby." },
    { word: "Writer", hint: "A person who uses written words to communicate ideas or stories." },
    { word: "Chef", hint: "A professional cook who prepares meals in restaurants or hotels." },
    { word: "Police", hint: "Members of a law enforcement agency who maintain public order and safety." },
    { word: "Pilot", hint: "A person who operates an aircraft and controls its flight." },
    { word: "Actor", hint: "A person who performs in plays, movies, or television shows." },
    { word: "Athlete", hint: "A person who engages in sports or other physical exercises professionally." },
    { word: "Singer", hint: "A person who uses their voice to perform musical pieces or songs." },
    { word: "Dentist", hint: "A medical professional who diagnoses and treats dental problems." },
    { word: "Architect", hint: "A person who designs buildings and oversees their construction." },
    { word: "Scientist", hint: "A person who conducts scientific research and experiments." },
    { word: "Plumber", hint: "A person who installs and repairs pipes and fixtures for water supply or drainage." },
    { word: "Banker", hint: "A person who works in the banking industry, handling financial transactions." },
    { word: "Carpenter", hint: "A person who works with wood, constructing and repairing structures." },
    { word: "Designer", hint: "A person who creates and plans the visual or functional aspects of objects." },
    { word: "Farmer", hint: "A person who cultivates crops and raises livestock for food production." },
    { word: "Mechanic", hint: "A person who repairs and maintains machinery and vehicles." },
    { word: "Translator", hint: "A person who converts written or spoken content from one language to another." },
    { word: "Happy", hint: "Feeling or showing pleasure or contentment." },
    { word: "Sad", hint: "Feeling or showing sorrow; unhappy." },
    { word: "Angry", hint: "Feeling or showing strong displeasure or rage." },
    { word: "Excited", hint: "Feeling or showing enthusiasm or eagerness." },
    { word: "Nervous", hint: "Feeling or showing anxiety or unease." },
    { word: "Surprised", hint: "Feeling or showing astonishment or wonder." },
    { word: "Anxious", hint: "Feeling or showing unease or worry about something uncertain." },
    { word: "Calm", hint: "Peaceful and free from agitation or excitement." },
    { word: "Confident", hint: "Having belief in oneself; self-assured." },
    { word: "Proud", hint: "Feeling deep pleasure or satisfaction as a result of one's achievements." },
    { word: "Jealous", hint: "Feeling or showing envy or resentment towards someone else's possessions, qualities, or achievements." },
    { word: "Hopeful", hint: "Feeling or inspiring optimism about a future event or outcome." },
    { word: "Lonely", hint: "Feeling sad and dejected due to the absence or lack of companionship." },
    { word: "Grateful", hint: "Feeling or expressing appreciation or thanks." },
    { word: "Loved", hint: "Feeling or being the object of affection or deep emotional attachment." },
    { word: "Bored", hint: "Feeling weary and uninterested due to lack of excitement or engagement." },
    { word: "Relaxed", hint: "Feeling free from tension or anxiety; at ease." },
    { word: "Hurt", hint: "Feeling emotional pain or distress." },
    { word: "Content", hint: "Feeling a sense of satisfaction and fulfillment." },
    { word: "Amazed", hint: "Feeling or showing great wonder or surprise." },
    { word: "Curious", hint: "Eager to know or learn something." },
    { word: "Stressed", hint: "Feeling mental or emotional strain or tension." },
    { word: "Insecure", hint: "Feeling uncertain, lacking confidence, or being anxious about oneself or one's abilities." },
    { word: "Glad", hint: "Feeling pleasure, joy, or delight." },
    { word: "Ashamed", hint: "Feeling shame or guilt due to one's actions or behavior." },
    { word: "Worried", hint: "Feeling anxious or troubled about actual or potential problems." },
    { word: "Football", hint: "A team sport played with a round ball on a rectangular field, with the objective of scoring goals." },
    { word: "Basketball", hint: "A team sport played on a court, in which two teams try to score points by shooting a ball through a hoop." },
    { word: "Swimming", hint: "The activity or sport of moving through water by using the limbs, often for recreation or competition." },
    { word: "Tennis", hint: "A racket sport played by two or four players on a rectangular court, with the aim of hitting a ball over a net." },
    { word: "Golf", hint: "A precision club-and-ball sport played on a course, in which players use various clubs to hit balls into a series of holes." },
    { word: "Running", hint: "The action or sport of moving swiftly on foot, typically at a faster pace than walking or jogging." },
    { word: "Cycling", hint: "The activity or sport of riding a bicycle, typically for transportation, recreation, or sport." },
    { word: "Soccer", hint: "Another term for football, popularly used in North America and some other countries." },
    { word: "Baseball", hint: "A bat-and-ball sport played between two teams, in which players try to hit a ball and score runs." },
    { word: "Hockey", hint: "A fast-paced team sport played on ice or field, in which players use sticks to hit a small rubber puck or ball." },
    { word: "Volleyball", hint: "A team sport played on a court, in which two teams hit a ball back and forth over a net, trying to score points." },
    { word: "Boxing", hint: "A combat sport in which two people engage in a contest of strength, speed, reflexes, and endurance." },
    { word: "Rugby", hint: "A team sport played with an oval ball, in which players carry, kick, or pass the ball to score points." },
    { word: "Cricket", hint: "A bat-and-ball sport played between two teams, in which players try to score runs and take wickets." },
    { word: "Gym", hint: "A facility or space equipped for indoor sports, exercise, or physical fitness training." },
    { word: "Martial", hint: "Relating to or characteristic of war or warriors; often used in conjunction with arts, such as martial arts." },
    { word: "Skiing", hint: "The activity or sport of sliding down snow-covered hills or mountains on skis." },
    { word: "Surfing", hint: "The sport or activity of riding on the crest or along the face of a wave, typically while standing or lying on a surfboard." },
    { word: "Yoga", hint: "A physical, mental, and spiritual practice that originated in ancient India, involving postures, breathing, and meditation." },
    { word: "Badminton", hint: "A racket sport played with a shuttlecock, in which players hit it back and forth over a net." },
    { word: "Table", hint: "A sport played on a flat table divided by a net, with players using paddles to hit a small ball back and forth." },
    { word: "Diving", hint: "The sport or activity of jumping or falling into water from a platform or springboard." },
    { word: "Bowling", hint: "A sport or leisure activity in which a player rolls a bowling ball to knock down pins." },
    { word: "Wrestling", hint: "A combat sport involving grappling techniques, throws, holds, and pinning an opponent to the ground." },
    { word: "Skating", hint: "The action or sport of gliding on ice or rolling on wheels over a surface." },
    { word: "Hiking", hint: "The activity of going for long walks, especially in natural environments or countryside." },
    { word: "Fencing", hint: "A sport involving the use of swords, with the objective of outscoring or touching an opponent." },
    { word: "Run", hint: "To move swiftly on foot; to go at a fast pace using legs." },
    { word: "Jump", hint: "To propel oneself upwards into the air using legs or feet." },
    { word: "Swim", hint: "To move through water by using arms and legs." },
    { word: "Eat", hint: "To consume food by putting it into the mouth and chewing." },
    { word: "Sleep", hint: "To rest and slumber; to be in a state of rest during the night or day." },
    { word: "Read", hint: "To look at and understand written or printed words." },
    { word: "Write", hint: "To form letters, words, or symbols on a surface using a pen or pencil." },
    { word: "Dance", hint: "To move rhythmically to music, typically following a choreographed sequence." },
    { word: "Sing", hint: "To produce musical sounds using the voice." },
    { word: "Talk", hint: "To communicate by speaking; to have a conversation." },
    { word: "Listen", hint: "To give attention and focus to sounds or spoken words." },
    { word: "Laugh", hint: "To express amusement or joy by making sounds with the mouth." },
    { word: "Cry", hint: "To shed tears as an expression of sadness, pain, or emotion." },
    { word: "Smile", hint: "To form one's mouth into an upward curved shape as an expression of happiness or friendliness." },
    { word: "Play", hint: "To engage in an activity for amusement or recreation." },
    { word: "Work", hint: "To exert effort in order to accomplish a task or achieve a goal." },
    { word: "Study", hint: "To acquire knowledge or skills through learning and focused attention." },
    { word: "Run", hint: "To move swiftly on foot; to go at a fast pace using legs." },
    { word: "Jump", hint: "To propel oneself upwards into the air using legs or feet." },
    { word: "Swim", hint: "To move through water by using arms and legs." },
    { word: "Eat", hint: "To consume food by putting it into the mouth and chewing." },
    { word: "Sleep", hint: "To rest and slumber; to be in a state of rest during the night or day." },
    { word: "Read", hint: "To look at and understand written or printed words." },
    { word: "Write", hint: "To form letters, words, or symbols on a surface using a pen or pencil." },
    { word: "Dance", hint: "To move rhythmically to music, typically following a choreographed sequence." },
    { word: "Sing", hint: "To produce musical sounds using the voice." },
    { word: "Talk", hint: "To communicate by speaking; to have a conversation." },
    { word: "Listen", hint: "To give attention and focus to sounds or spoken words." },
    { word: "Laugh", hint: "To express amusement or joy by making sounds with the mouth." },
    { word: "Cry", hint: "To shed tears as an expression of sadness, pain, or emotion." },
    { word: "Smile", hint: "To form one's mouth into an upward curved shape as an expression of happiness or friendliness." },
    { word: "Play", hint: "To engage in an activity for amusement or recreation." },
    { word: "Work", hint: "To exert effort in order to accomplish a task or achieve a goal." },
    { word: "Study", hint: "To acquire knowledge or skills through learning and focused attention." },
    { word: "Sweet", hint: "Having a taste similar to sugar; not sour, bitter, or salty." },
    { word: "Sour", hint: "Having an acidic or sharp taste, often associated with lemons or vinegar." },
    { word: "Bitter", hint: "Having a strong, sharp taste that is not sweet." },
    { word: "Salty", hint: "Containing or tasting like salt; having a flavor of salt." },
    { word: "Spicy", hint: "Having a pungent, hot, or strong flavor due to the presence of spices." },
    { word: "Savory", hint: "Pleasant to the taste; having a full, rich flavor." },
    { word: "Tangy", hint: "Having a sharp, piquant flavor; pleasantly sharp or tart." },
    { word: "Delicious", hint: "Highly pleasing to the taste; very tasty or flavorful." },
    { word: "Succulent", hint: "Juicy and tender, often used to describe well-cooked meat or ripe fruits." },
    { word: "Aromatic", hint: "Having a strong and pleasant smell; fragrant." },
    { word: "Ripe", hint: "Fully matured and ready to eat, often used to describe fruits or vegetables." },
    { word: "Zesty", hint: "Having a strong, lively, and somewhat spicy flavor." },
    { word: "Mild", hint: "Not strong or intense in flavor; gentle on the palate." },
    { word: "Tasty", hint: "Having a pleasant and agreeable flavor." },
    { word: "Flavorful", hint: "Having a rich and distinctive taste; full of flavor." },
    { word: "Herbaceous", hint: "Having the characteristics of herbs; often used to describe fresh, green flavors." },
    { word: "Acidic", hint: "Having a pH level below 7; often used to describe a sour taste." },
    { word: "Buttery", hint: "Having a rich and smooth taste like butter." },
    { word: "Peppery", hint: "Having a pungent, hot flavor like that of black pepper." },
    { word: "Juicy", hint: "Full of juice; having a lot of liquid content." },
    { word: "Astringent", hint: "Having a sharp, bitter taste that causes the contraction of body tissues." },
    { word: "Sapid", hint: "Having a strong and pleasant taste; flavorful." },
    { word: "Minty", hint: "Having a fresh, cool flavor like that of mint leaves." },
    { word: "Tart", hint: "Having a sharp, sour taste; pleasantly sharp or acid in flavor." },
    { word: "Robust", hint: "Having a strong and full-bodied flavor." },
    { word: "Nutty", hint: "Having a flavor or aroma reminiscent of nuts." },
    { word: "Woody", hint: "Having a taste or aroma suggestive of wood, often used to describe certain wines." },
    { word: "Earthy", hint: "Having a taste or aroma suggestive of soil or earth, often used to describe certain vegetables or wines." },
    { word: "Rich", hint: "Abundant in flavor, often used to describe foods with a high fat content." },
    { word: "Pungent", hint: "Having a strong, sharp taste or smell." },
    { word: "Mellow", hint: "Having a smooth, soft, and pleasing flavor." },
    { word: "Computer", hint: "An electronic device that can store, retrieve, and process data." },
    { word: "Smartphone", hint: "A mobile phone that has advanced computing capabilities and connectivity." },
    { word: "Television", hint: "An electronic device used for receiving and displaying broadcast signals." },
    { word: "Microwave", hint: "An appliance that uses electromagnetic waves to cook or heat food quickly." },
    { word: "Camera", hint: "A device used to capture still or moving images." },
    { word: "Headphones", hint: "A pair of small speakers worn over the ears to listen to audio privately." },
    { word: "Tablet", hint: "A portable device with a touchscreen display, typically used for browsing, reading, and entertainment." },
    { word: "Laptop", hint: "A portable computer designed to be used on a person's lap or on a flat surface." },
    { word: "Printer", hint: "A device that produces text or graphics on paper or other media." },
    { word: "Router", hint: "A device that forwards data packets between computer networks." },
    { word: "Projector", hint: "A device that projects images or videos onto a screen or wall." },
    { word: "Monitor", hint: "A display screen used to view output from a computer or other electronic device." },
    { word: "Keyboard", hint: "An input device used to enter text and commands into a computer." },
    { word: "Mouse", hint: "An input device used to control the cursor on a computer screen." },
    { word: "Scanner", hint: "A device that captures images or text and converts them into digital format." },
    { word: "Speaker", hint: "A device that converts electrical signals into sound waves." },
    { word: "Clock", hint: "A timekeeping device used to measure and indicate time." },
    { word: "Fan", hint: "An electric device used for creating a flow of air to provide cooling or ventilation." },
    { word: "Router", hint: "A device that forwards data packets between computer networks." },
    { word: "Projector", hint: "A device that projects images or videos onto a screen or wall." },
    { word: "Monitor", hint: "A display screen used to view output from a computer or other electronic device." },
    { word: "Keyboard", hint: "An input device used to enter text and commands into a computer." },
    { word: "Mouse", hint: "An input device used to control the cursor on a computer screen." },
    { word: "Scanner", hint: "A device that captures images or text and converts them into digital format." },
    { word: "Speaker", hint: "A device that converts electrical signals into sound waves." },
    { word: "Clock", hint: "A timekeeping device used to measure and indicate time." },
    { word: "Fan", hint: "An electric device used for creating a flow of air to provide cooling or ventilation." },
    { word: "Drone", hint: "An unmanned aerial vehicle controlled either autonomously or by a remote pilot." },
    { word: "Gamepad", hint: "A handheld device used to control video games on a gaming console or computer." },
    { word: "Router", hint: "A device that forwards data packets between computer networks." } 
]
